version: '3.7'

services:
    rmg:
      image: docker.pkg.github.com/qtc-de/remote-method-guesser/rmg-example-server:1.0
      #      environment:
      #        - > 
      #          _JAVA_OPTIONS=
      #          -Djava.rmi.server.hostname=iinsecure.dev
      #          -Djavax.net.ssl.keyStorePassword=password
      #          -Djavax.net.ssl.keyStore=/opt/store.p12
      #          -Djavax.net.ssl.keyStoreType=pkcs12
      #      volumes: 
      #        - ./resources/trust/store.p12:/opt/store.p12
      #        - ./resources/rmg-example-server.jar:/opt/example-server.jar
      #        - ./resources/rmg-legacy-server.jar:/opt/example-server.jar
      #        - ./resources/commons-collections-3.1.jar:/usr/lib/jvm/java-1.8-openjdk/jre/lib/ext/commons-collections-3.1.jar
